# Generated by Django 5.2.7 on 2025-10-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='Внешняя ссылка'),
        ),
    ]
