# Generated by Django 5.2.7 on 2025-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_section_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/', verbose_name='Изображение'),
        ),
    ]
