# Generated by Django 5.2.7 on 2025-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='interactive_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные для интерактивного задания'),
        ),
    ]
