# Generated by Django 5.2.7 on 2025-10-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_section_interactive_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='section_files/', verbose_name='Приложенный файл'),
        ),
    ]
