# Generated by Django 5.2.7 on 2025-10-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_feedback_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_admins', models.BooleanField(default=True, verbose_name='Уведомлять администраторов')),
                ('notify_emails', models.TextField(blank=True, help_text='По одному email на строку', verbose_name='Дополнительные email для уведомлений')),
                ('auto_response_enabled', models.BooleanField(default=True, verbose_name='Включить авто-ответ пользователю')),
                ('auto_response_subject', models.CharField(default='Мы получили ваше обращение', max_length=200, verbose_name='Тема авто-ответа')),
                ('auto_response_message', models.TextField(default='Благодарим за обращение! Мы рассмотрим его в ближайшее время.', verbose_name='Текст авто-ответа')),
                ('feedback_email', models.EmailField(default='great.egor7288@yandex.ru', max_length=254, verbose_name='Email для ответов на обращения')),
            ],
            options={
                'verbose_name': 'Настройка обратной связи',
                'verbose_name_plural': 'Настройки обратной связи',
            },
        ),
    ]
