# Generated by Django 5.2.7 on 2025-10-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0009_userreadingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReadingSession',
        ),
    ]
