# Generated by Django 5.2.7 on 2025-10-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_delete_userreadingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='javascript_code',
            field=models.TextField(blank=True, help_text='Вставьте полный JavaScript код для интерактивного задания', null=True, verbose_name='JavaScript код интерактивного задания'),
        ),
    ]
