# Generated by Django 5.2.7 on 2025-10-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_section_javascript_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='interactive_data',
        ),
    ]
