# Generated by Django 5.2.8 on 2025-11-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0012_remove_section_interactive_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='javascript_code',
        ),
    ]
