# Generated by Django 5.2.8 on 2025-11-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_remove_section_javascript_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл (MP4, WebM, OGG)', null=True, upload_to='section_videos/', verbose_name='Видео файл'),
        ),
        migrations.AddField(
            model_name='section',
            name='video_url',
            field=models.URLField(blank=True, help_text='Или укажите ссылку на YouTube/Vimeo', verbose_name='Ссылка на видео'),
        ),
    ]
