# Generated by Django 6.0 on 2025-12-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0014_section_video_file_section_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
